// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
        //jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        //jcenter()
    }
    ext {
        LIBRARY_COMPILE_SDK_VERSION = 36
        LIBRARY_BUILD_TOOLS_VERSION = "36.0.0"
        LIBRARY_MIN_SDK_VERSION = 16
        LIBRARY_TARGET_SDK_VERSION = 36
    }
}
